frontend/controllers/EstudiantecarreracaController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\ca\Estudiantecarreraca;
use app\models\ca\EstudiantecarreracaSearch;
use frontend\components\DefaultController;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EstudiantecarreracaController implements the CRUD actions for Estudiantecarreraca model.
 */
class EstudiantecarreracaController extends DefaultController
{
    // /**
    //  * @inheritdoc
    //  */
    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['POST'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * Lists all Estudiantecarreraca models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EstudiantecarreracaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Estudiantecarreraca model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Estudiantecarreraca model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Estudiantecarreraca();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_estudiante_carrera]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Estudiantecarreraca model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_estudiante_carrera]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Estudiantecarreraca model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Estudiantecarreraca model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Estudiantecarreraca the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Estudiantecarreraca::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

use app\models\ca\Estudiantecarreraca;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        // return [
        //     'access' => [
        //         'class' => AccessControl::className(),
        //         'only' => ['logout', 'signup'],
        //         'rules' => [
        //             [
        //                 'actions' => ['signup'],
        //                 'allow' => true,
        //                 'roles' => ['?'],
        //             ],
        //             [
        //                 'actions' => ['logout'],
        //                 'allow' => true,
        //                 'roles' => ['@'],
        //             ],
        //         ],
        //     ],
        //     'verbs' => [
        //         'class' => VerbFilter::className(),
        //         'actions' => [
        //             'logout' => ['post'],
        //         ],
        //     ],
        // ];

        // implementando user-management
        return [
      		'ghost-access'=> [
      			'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
      		],
      	];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }


    public function actionIndexactas()
    {
        // $model = new Estudiantecarreraca();
        //
        // if ($model->load(Yii::$app->request->post())) {
        //     if ($model->validate()) {
        //         // form inputs are valid, do something here
        //         return;
        //     }
        // }

        return $this->render('indexactas', [
        ]);
    }

}

frontend/views/estudiantecarreraca/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Estudiantecarreraca */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="estudiantecarreraca-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'anio_inscripcion')->textInput() ?>

    <?= $form->field($model, 'fecha_cierre')->textInput() ?>

    <?= $form->field($model, 'fe_graduacion')->textInput() ?>

    <?= $form->field($model, 'estado')->textInput() ?>

    <?= $form->field($model, 'id_estudiante')->textInput() ?>

    <?= $form->field($model, 'id_carrera')->textInput() ?>

    <?= $form->field($model, 'id_sede')->textInput() ?>

    <?= $form->field($model, 'id_plan')->textInput() ?>

    <?= $form->field($model, 'id_sede_asig')->textInput() ?>

    <?= $form->field($model, 'id_plan_asig')->textInput() ?>

    <?= $form->field($model, 'id_carrera_origen')->textInput() ?>

    <?= $form->field($model, 'ua')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ext')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'car')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cierre_generado')->textInput() ?>

    <?= $form->field($model, 'codigoUltimoCurso')->textInput() ?>

    <?= $form->field($model, 'id_solicitud_cierre')->textInput() ?>

    <?= $form->field($model, 'id_pensum')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/estudiantecarreraca/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EstudiantecarreracaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="estudiantecarreraca-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_estudiante_carrera') ?>

    <?= $form->field($model, 'anio_inscripcion') ?>

    <?= $form->field($model, 'fecha_cierre') ?>

    <?= $form->field($model, 'fe_graduacion') ?>

    <?= $form->field($model, 'estado') ?>

    <?php // echo $form->field($model, 'id_estudiante') ?>

    <?php // echo $form->field($model, 'id_carrera') ?>

    <?php // echo $form->field($model, 'id_sede') ?>

    <?php // echo $form->field($model, 'id_plan') ?>

    <?php // echo $form->field($model, 'id_sede_asig') ?>

    <?php // echo $form->field($model, 'id_plan_asig') ?>

    <?php // echo $form->field($model, 'id_carrera_origen') ?>

    <?php // echo $form->field($model, 'ua') ?>

    <?php // echo $form->field($model, 'ext') ?>

    <?php // echo $form->field($model, 'car') ?>

    <?php // echo $form->field($model, 'cierre_generado') ?>

    <?php // echo $form->field($model, 'codigoUltimoCurso') ?>

    <?php // echo $form->field($model, 'id_solicitud_cierre') ?>

    <?php // echo $form->field($model, 'id_pensum') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/estudiantecarreraca/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Estudiantecarreraca */

$this->title = 'Create Estudiantecarreraca';
$this->params['breadcrumbs'][] = ['label' => 'Estudiantecarreracas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="estudiantecarreraca-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/estudiantecarreraca/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

use app\models\Carreraca;
/* @var $this yii\web\View */
/* @var $searchModel app\models\EstudiantecarreracaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Carreras por estudiante';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="estudiantecarreraca-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <!-- <?= Html::a('Create Estudiantecarreraca', ['create'], ['class' => 'btn btn-success']) ?> -->
        <?= Html::a('<i class="glyphicon glyphicon-arrow-left"></i> Regresar', ['site/indexactas'], ['class' => 'btn btn-danger']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
            ['class' => 'yii\grid\ActionColumn'],
            //'id_estudiante_carrera',
            //'anio_inscripcion',
            //'estado',
             // 'id_estudiante',
             // 'id_carrera',
             [
                 'label' => 'Carnet',
                 'filter' => true,
                 'value' => 'estudiante.carnet',
             ],
             [
                 'label' => 'Apellidos Nombres',
                 'filter' => true,
                 'value' => 'estudiante.nombres',
             ],
             'fecha_cierre',
             'fe_graduacion',
             [
                 'label' => 'Carrera',
                 'filter' => true,
                 'value' => 'carreraca.nombre',
             ],
            // 'id_sede',
            // 'id_plan',
            // 'id_sede_asig',
            // 'id_plan_asig',
            // 'id_carrera_origen',
            //  'ua',
            //  'ext',
            //  'car',
            // 'cierre_generado',
            // 'codigoUltimoCurso',
            // 'id_solicitud_cierre',
            // 'id_pensum',


        ],
    ]); ?>
<?php Pjax::end(); ?></div>

frontend/views/estudiantecarreraca/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Estudiantecarreraca */

$this->title = 'Update Estudiantecarreraca: ' . $model->id_estudiante_carrera;
$this->params['breadcrumbs'][] = ['label' => 'Estudiantecarreracas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_estudiante_carrera, 'url' => ['view', 'id' => $model->id_estudiante_carrera]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="estudiantecarreraca-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/estudiantecarreraca/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Estudiantecarreraca */

$this->title = $model->id_estudiante_carrera;
$this->params['breadcrumbs'][] = ['label' => 'Estudiantecarreracas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="estudiantecarreraca-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id_estudiante_carrera], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id_estudiante_carrera], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_estudiante_carrera',
            'anio_inscripcion',
            'fecha_cierre',
            'fe_graduacion',
            'estado',
            'id_estudiante',
            'id_carrera',
            'id_sede',
            'id_plan',
            'id_sede_asig',
            'id_plan_asig',
            'id_carrera_origen',
            'ua',
            'ext',
            'car',
            'cierre_generado',
            'codigoUltimoCurso',
            'id_solicitud_cierre',
            'id_pensum',
        ],
    ]) ?>

</div>