backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/CarreraController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Carrera;
use app\models\CarreraSearch;
use frontend\components\DefaultController;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CarreraController implements the CRUD actions for Carrera model.
 */
class CarreraController extends DefaultController
{
    // /**
    //  * @inheritdoc
    //  */
    // public function behaviors()
    // {
    //   return [
    //     'ghost-access'=> [
    //       'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
    //     ],
    //   ];
    // }

    /**
     * Lists all Carrera models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CarreraSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Carrera model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Carrera model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Carrera();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idCarrera]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Carrera model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idCarrera]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Carrera model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Carrera model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Carrera the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Carrera::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/CarreracaController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\ca\Carreraca;
use app\models\ca\CarreracaSearch;
use frontend\components\DefaultController;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CarreracaController implements the CRUD actions for Carreraca model.
 */
class CarreracaController extends DefaultController
{
    // /**
    //  * @inheritdoc
    //  */
    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['POST'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * Lists all Carreraca models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CarreracaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Carreraca model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Carreraca model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Carreraca();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_carrera]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Carreraca model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_carrera]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Carreraca model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Carreraca model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Carreraca the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Carreraca::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/ExtensionController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Extension;
use app\models\ExtensionSearch;
use frontend\components\DefaultController;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ExtensionController implements the CRUD actions for Extension model.
 */
class ExtensionController extends DefaultController
{
    // /**
    //  * @inheritdoc
    //  */
    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['POST'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * Lists all Extension models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ExtensionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Extension model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Extension model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Extension();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idExtension]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Extension model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idExtension]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Extension model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Extension model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Extension the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Extension::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Acerca de la Facultad de Humanidades';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <h3>Historia de la Facultad</h3>

    <p>El 19 de noviembre de 1944, la Junta Revolucionaria de Gobierno, emitió el decreto No. 12, por medio del cual se otorgaba autonomía a la Universidad de San Carlos de Guatemala. Entró en vigencia el 1 de diciembre del mismo año e indicaba, en el Artículo 3o.La integración de la Universidad por siete facultades, entre ellas la Facultad de Humanidades.
El 17 de septiembre de 1945, mediante el acta N0. 78, punto decimosexto, el Consejo Superior Universitario funda la Facultad de Humanidades, integrando el pensamiento universitario, mediante una visión conjunta y universal de los problemas del hombre y el mundo.
Investigar en los campos de las disciplinas filosóficas, históricas, literarias, pedagógicas, psicológicas, lingüísticas, y en los que con ellas guardan afinidad y analogía.
Crear una amplia y generosa conciencia social en el conglomerado universitario, a fin de articular la función de la Universidad y de sus estudiantes y egresados con las altas finalidades de la colectividad.
</p>

<div class="row">
  <div class="col-md-6">
    <h3>Misión</h3>
    <p>La formación de profesionales con excelencia académica en las distintas áreas humanísticas, que incide en la solución de los problemas de la realidad nacional.</p>
  </div>
  <div class="col-md-6">
    <h3>Visión</h3>
    <p>Ser la entidad rectora en la formación de profesionales humanistas, con base científica y tecnológica de acuerdo con el momento socioeconómico, cultural, geopolítico y educativo, con impacto en las políticas de desarrollo nacional, regional e internacional.</p>
  </div>
</div>
<!--
app\models\Estudianteca
app\models\EstudiantecaQuery
app\models\EstudiantecaSearch
frontend\controllers\EstudiantecaController
@app/views/estudianteca

app\models\ca\Carreraca
app\models\ca\CarreracaQuery
app\models\ca\CarreracaSearch
frontend\controllers\CarreracaController
@app/views/carreraca

app\models\Estudiantecarreraca
app\models\EstudiantecarreracaQuery
app\models\EstudiantecarreracaSearch
frontend\controllers\EstudiantecarreracaController
@app/views/estudiantecarreraca
-->




    <!--<code><?= __FILE__ ?></code>-->
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <!--<?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>-->

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <!-- <p>
        The above error occurred while the Web server was processing your request.
    </p>

    <p>
        Please contact us if you think this is a server error. Thank you.
    </p> -->

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;

use webvimark\modules\UserManagement\components\GhostMenu;
use webvimark\modules\UserManagement\UserManagementModule;

$this->title = 'Fac.Humanidades';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Facultad de Humanidades, USAC</h1>

        <p class="lead">Portal de acceso al Módulo de Emisión de Actas de Graduación y al Sistema de asignación y control de EPS.</p>




    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-3">
                <h2>EPS</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua.</p>
                <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Control de EPS &raquo;</a></p>
            </div>
            <div class="col-lg-3">
                <h2>Privados</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua.</p>

                <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Asignación Privados &raquo;</a></p>
            </div>
            <div class="col-lg-3">
                <h2>Base viejita</h2>

                <p>

                </p>
                <div class="row">
                  <div class="col-md-6">
                    <ul class="nav nav-stacked">
                      <li role="presentation"><?= Html::a('Extension', ['extension/index'], ['class' => 'btn btn-link']) ?></li>
                      <li role="presentation"><?= Html::a('Carrera', ['carrera/index'], ['class' => 'btn btn-link']) ?></li>
                      <li role="presentation"><?= Html::a('Examinador', ['examinador/index'], ['class' => 'btn btn-link']) ?></li>
                      <li role="presentation"><?= Html::a('Actas', ['informacion/index'], ['class' => 'btn btn-link']) ?></li>
                    </ul>
                  </div>
                </div>
            </div>
            <div class="col-lg-3">
              <h2>Emisión de Actas</h2>

              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua.</p>
              <p><a class="btn btn-lg btn-success" href="site/indexactas">Control de Actas de Graduación</a></p>
            </div>
        </div>

    </div>

    <div class="body-content">
        <div class="row">
            <div class="col-md-4">
              <?php
                echo GhostMenu::widget([
                	'encodeLabels'=>false,
                	'activateParents'=>true,
                	'items' => [
                		[
                			'label' => 'Backend routes',
                			'items'=>UserManagementModule::menuItems()
                		],
                		[
                			'label' => 'Frontend routes',
                			'items'=>[
                				['label'=>'Login', 'url'=>['/user-management/auth/login']],
                				['label'=>'Logout', 'url'=>['/user-management/auth/logout']],
                				['label'=>'Registration', 'url'=>['/user-management/auth/registration']],
                				['label'=>'Change own password', 'url'=>['/user-management/auth/change-own-password']],
                				['label'=>'Password recovery', 'url'=>['/user-management/auth/password-recovery']],
                				['label'=>'E-mail confirmation', 'url'=>['/user-management/auth/confirm-email']],
                			],
                		],
                	],
                ]);

                echo GhostMenu::widget([
                	'encodeLabels'=>false,
                	'activateParents'=>true,
                	'items' => [
                		[
                			'label' => 'Base de Extension',
                			'items'=>[
                				['label'=>'extension', 'url'=>['extension/index']],
                        ['label'=>'carrera', 'url'=>['carrera/index']],
                        ['label'=>'examinador', 'url'=>['examinador/index']],
                        ['label'=>'actas', 'url'=>['actas/index']],
                				
                			],
                		],
                	],
                ]);

              ?>
            </div>
        </div>
    </div>
</div>

frontend/views/site/indexactas.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ca\Estudiantecarreraca */
/* @var $form ActiveForm */
?>
<div class="">

  <div class="row">
    <div class="col-md-3">
      <h2>Ctrl. Académico.</h2>
      <ul class="nav nav-stacked">
        <li role="presentation"><?= Html::a('Estudiante',         ['estudianteca/index','sort'=>'-carnet'], ['class' => 'btn btn-link']) ?></li>
        <li role="presentation"><?= Html::a('Estudiante-Carrera', ['estudiantecarreraca/index','sort'=>'-id_estudiante'], ['class' => 'btn btn-link']) ?></li>
        <li role="presentation"><?= Html::a('Carrera',            ['carreraca/index'], ['class' => 'btn btn-link']) ?></li>
      </ul>
    </div>
    <div class="col-md-3">
      <h2>Emisión de Actas</h2>
      <ul class="nav nav-stacked">
        <li role="presentation"><?= Html::a('Estudiante',         ['estudianteca/index','sort'=>'-carnet'], ['class' => 'btn btn-link']) ?></li>
        <li role="presentation"><?= Html::a('Estudiante-Carrera', ['estudiantecarreraca/index','sort'=>'-id_estudiante'], ['class' => 'btn btn-link']) ?></li>
        <li role="presentation"><?= Html::a('Carrera',            ['carreraca/index'], ['class' => 'btn btn-link']) ?></li>
      </ul>
    </div>
  </div>

</div><!-- site-indexactas -->

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>